apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    team: yarismadevelopersteam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - image: veyselky/userservice:v101
          name: poduser
          resources:
            requests:
              memory: "1Gi"
              cpu : "0.1"
            limits:
              memory: "2Gi"
              cpu: "250m"
          ports:
            - containerPort: 9092
          env:
            - name: user_port
              valueFrom: 
                secretKeyRef:
                  name: yarismasecret
                  key: user_port
            - name: db_mongo_userName
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: db_mongo_userName
            - name: db_mongo_password
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: db_mongo_password
            - name: db_mongo_port
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: db_mongo_port
            - name: db_mongo_database
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: db_mongo_database
            - name: db_mongo_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: db_mongo_url
            - name: auth_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: auth_url
            - name: main_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: main_url
            - name: user_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: user_url
            - name: config_server_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: config_server_url
            - name: rabbitmq_host
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: rabbitmq_host
            - name: rabbitmq_port
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: rabbitmq_port
            - name: rabbitmq_userName
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: rabbitmq_userName
            - name: rabbitmq_password
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: rabbitmq_password
            - name: zipkin_url
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: zipkin_url
            - name: redis_host
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: redis_host
            - name: redis_port
              valueFrom:
                secretKeyRef:
                  name: yarismasecret
                  key: redis_port
                  