apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-gateway
spec:
  selector:
#    app: gateway-service
#    redis: pod-redis
#    elastic: pod-elasticsearch
#    app: pod-zipkin
    app: user-service
  type: LoadBalancer
  ports:
    - name: test
      port: 9092
      targetPort: 9092
