package com.vky.utility;

import com.vky.dto.request.RegisterRequestDto;
import com.vky.repository.enums.Roles;
import com.vky.service.AuthService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;

@Component
@RequiredArgsConstructor
public class AuthImpl {
    private final AuthService authService;

//    @PostConstruct
    public void init()
    {
        for (int i = 0; i < 1000; i++) {
            authService.register(RegisterRequestDto.builder()
                    .userName("admin")
                    .email("admin@admin.com")
                    .password("123123")
                    .role(Roles.ADMIN)
                    .RoleAdminPassword("123456")
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("sinan")
                    .email("ali@gmail.com")
                    .password("123123")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("gizem")
                    .email("gizem@gmail.com")
                    .password("123123")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("kenan")
                    .email("kenan@gmail.com")
                    .password("123123")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("hilal")
                    .email("hilal@gmail.com")
                    .password("123123")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("furkan")
                    .email("furkan@gmail.com")
                    .password("123123")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("baris")
                    .email("baris@gmail.com")
                    .password("123123")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("enes")
                    .email("enes@gmail.com")
                    .password("123123")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("buse")
                    .email("buse@gmail.com")
                    .password("123123")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("fatih")
                    .email("fatih@gmail.com")
                    .password("123123")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("beyza")
                    .email("beyza@gmail.com")
                    .password("123123")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("serpil")
                    .email("serpil@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("deniz")
                    .email("deniz@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("bahar")
                    .email("bahat@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("tekin")
                    .email("tekin@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("berk")
                    .email("berk@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("cansu")
                    .email("cansu@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("zeynep")
                    .email("zeynep@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("akın")
                    .email("akın@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("ahmet")
                    .email("ahmet@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("ceren")
                    .email("ceren@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("ersin")
                    .email("ersin@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("ferhat")
                    .email("ferhat@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("gunes")
                    .email("gunes@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("hakkı")
                    .email("hakki@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
            authService.register(RegisterRequestDto.builder()
                    .userName("kerim")
                    .email("kerim@uygulama.com")
                    .password("123456")
                    .role(Roles.USER)
                    .build());
        }
    }
}
